import Head from 'next/head'
import NavBar from './components/navbar'
import ApartmentCard from './components/cityApartments/cityApartmentCard';
import { useAuthContext } from '../../hooks/useAuth';
import { useEffect, useState } from 'react';
import { getAllApartments } from './api/endpoints';


export default function DepasMaza() {
    const [apartmentData, setApartmentData] = useState([]);
    const { user, authenticated, error, register, login, logout, isAdmin } = useAuthContext();

    useEffect(() => {
        (async () => {
            if (user) {
                const apartments = await getAllApartments(user.access_token);
                setApartmentData(apartments);
            }
        })();
    }, []);


    return (
        <div className="bg-slate-200 h-screen">
            <Head>
                <title>Mazatlan</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <main className="block m-auto md:flex md:pt-24 h-max xl:w-2/4 bg-slate-200">
                {apartmentData.map((item, index) => {
                    if (index <= 1) {
                        return;
                    }
                    return (
                        <ApartmentCard data={item} />
                    );
                })}
            </main>
        </div>
    )
}