import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import NavBar from './components/navbar'
import { useRouter } from 'next/router';
import { useAuthContext } from '../../hooks/useAuth';
import PhoneInput from 'react-phone-input-2'
import 'react-phone-input-2/lib/style.css'


export default function Login() {
    const { user, authenticated, error, register, login, isAdmin } = useAuthContext();
    const router = useRouter();

    const handleRegister = (event) => {
        event.preventDefault();
        const { name, email, password, confirmPassword, phone } = event.target.elements;

        if (password.value !== confirmPassword.value) {
            alert('Passwords dont match, try again.')
            return;
        }

        const numWSpaces = phone.value.split("+");
        const num = numWSpaces[1].split(" ").join("");
        const userData = {
            name: name.value,
            password: password.value,
            repeatPassword: confirmPassword.value,
            email: email.value,
            phoneNumber: num
        };

        const res = register(userData);
        res.then((response) => {
            if (!response) { alert("This email is already in use, try a different one.") } else {
                alert('Successfully registered the user, login.');
            }
        })

    };

    const handleLogin = (event) => {
        event.preventDefault();
        const { emailLogin, passwordLogin } = event.target.elements;

        const credentials = {
            email: emailLogin.value,
            password: passwordLogin.value,
        };
        const res = login(credentials).then((result) => {
            if (result) {
                alert('Successfully Logged In!');
                router.push('/en');
            }
            if (result === undefined) {
                alert('Wrong data, try again.')
            }
        });

    };
    return (
        <div className={styles.container}>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <main className=" w-full h-fit pt-20 bg-slate-200">
                <div className="container mx-auto py-8">
                    <h1 className="text-2xl font-bold mb-6 text-center text-slate-800">Create an Account</h1>
                    <form className="w-full max-w-sm mx-auto bg-white p-8 rounded-md shadow-md" onSubmit={handleRegister}>
                        <div className="mb-4">
                            <label className="block text-gray-700 text-sm font-bold mb-2" for="name">Name</label>
                            <input className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500"
                                type="text" id="name" name="name" placeholder="John Smith" required={true}></input>
                        </div>
                        <div className="mb-4">
                            <label className="block text-gray-700 text-sm font-bold mb-2" for="email">Email</label>
                            <input className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500"
                                type="email" id="email" name="email" placeholder="user@example.com" required={true}></input>
                        </div>
                        <div className="mb-4 text-slate-800">
                            <label className="block text-gray-700 text-sm font-bold mb-2" for="email">Phone</label>
                            <PhoneInput country={'us'} placeholder='5434336830' inputProps={{ required: true, name: 'phone' }} />
                            {/* <input className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500"
                                type="text" id="phone" name="phone" placeholder="526681334394" required={true}></input> */}
                        </div>
                        <div className="mb-4">
                            <label className="block text-gray-700 text-sm font-bold mb-2" for="password">Password</label>
                            <input className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500"
                                type="password" id="password" name="password" placeholder="********" required={true}></input>
                        </div>
                        <div className="mb-4">
                            <label className="block text-gray-700 text-sm font-bold mb-2" for="confirm-password">Confirm Password</label>
                            <input className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500"
                                type="password" id="confirmPassword" name="confirmPassword" placeholder="********" required={true}></input>
                        </div>
                        <button
                            className="bg-orange-400 w-full hover:bg-gray-100 text-slate-100 font-semibold py-2 px-4 border border-orange-700 rounded shadow"
                            type="submit">Register</button>
                    </form>
                </div>
                <div className="container mx-auto py-8">
                    <h1 className="text-2xl font-bold mb-6 text-center text-slate-800">LogIn</h1>
                    <form className="w-full max-w-sm mx-auto bg-white p-8 rounded-md shadow-md" onSubmit={handleLogin}>
                        <div className="mb-4">
                            <label className="block text-gray-700 text-sm font-bold mb-2" for="email">Email</label>
                            <input className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500"
                                type="email" id="emailLogin" name="emailLogin" placeholder="user@example.com" required={true}></input>
                        </div>
                        <div className="mb-4">
                            <label className="block text-gray-700 text-sm font-bold mb-2" for="password">Password</label>
                            <input className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500"
                                type="password" id="passwordLogin" name="passwordLogin" placeholder="********" required={true}></input>
                        </div>
                        <button
                            className="w-full bg-orange-400 hover:bg-gray-100 text-slate-100 font-semibold py-2 px-4 border border-orange-700 rounded shadow"
                            type="submit">Login</button>
                    </form>
                </div>
            </main>

        </div>
    )
}