import Head from "next/head";
import styles from "../styles/Home.module.css";
import NavBar from "../components/navbar";
import Depas from "./depas";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className=" w-full h-screen flex flex-wrap">
        <Depas></Depas>
      </main>

    </div>
  );
}
