import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-lime-600">
        <h1>HELLO WORLD</h1>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
