import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from '../components/navbar'

export default function Login() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <main className=" w-full h-fit pt-20 bg-slate-200">
                <div class="container mx-auto py-8">
                    <h1 class="text-2xl font-bold mb-6 text-center text-slate-800">Crea una cuenta</h1>
                    <form class="w-full max-w-sm mx-auto bg-white p-8 rounded-md shadow-md">
                        <div class="mb-4">
                            <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Nombre</label>
                            <input class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500"
                                type="text" id="name" name="name" placeholder="Juan Sanchez"></input>
                        </div>
                        <div class="mb-4">
                            <label class="block text-gray-700 text-sm font-bold mb-2" for="email">Correo</label>
                            <input class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500"
                                type="email" id="email" name="email" placeholder="usuario@ejemplo.com"></input>
                        </div>
                        <div class="mb-4">
                            <label class="block text-gray-700 text-sm font-bold mb-2" for="password">Clave</label>
                            <input class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500"
                                type="password" id="password" name="password" placeholder="********"></input>
                        </div>
                        <div class="mb-4">
                            <label class="block text-gray-700 text-sm font-bold mb-2" for="confirm-password">Confirmar Clave</label>
                            <input class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500"
                                type="password" id="confirm-password" name="confirm-password" placeholder="********"></input>
                        </div>
                        <button
                            class="bg-orange-400 w-full hover:bg-gray-100 text-slate-100 font-semibold py-2 px-4 border border-orange-700 rounded shadow"
                            type="submit">Registrarse</button>
                    </form>
                </div>
                <div class="container mx-auto py-8">
                    <h1 class="text-2xl font-bold mb-6 text-center text-slate-800">Inicia Sesion</h1>
                    <form class="w-full max-w-sm mx-auto bg-white p-8 rounded-md shadow-md">
                        <div class="mb-4">
                            <label class="block text-gray-700 text-sm font-bold mb-2" for="email">Correo</label>
                            <input class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500"
                                type="email" id="email" name="email" placeholder="usuario@ejemplo.com"></input>
                        </div>
                        <div class="mb-4">
                            <label class="block text-gray-700 text-sm font-bold mb-2" for="password">Clave</label>
                            <input class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500"
                                type="password" id="password" name="password" placeholder="********"></input>
                        </div>
                        <button
                            class="w-full bg-orange-400 hover:bg-gray-100 text-slate-100 font-semibold py-2 px-4 border border-orange-700 rounded shadow"
                            type="submit">Login</button>
                    </form>
                </div>
            </main>

        </div>
    )
}