import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from '../components/navbar'

export default function Login() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <main className=" w-full h-screen">
                <div className="w-full h-1/2 bg-[url('/locations/losCabos.jpg')] bg-cover relative bg-center bg-no-repeat flex justify-center">
                    <Link className='absolute z-10 text-slate-100 w-fit bg-orange-400 bg-opacity-90 border border-orange-500 p-4 top-36 font-bold rounded' href='/depasBaja'>Los Cabos, Baja California Sur</Link>
                    <div className='bg-orange-400 w-full bg-opacity-20 backdrop-blur-sm rounded absolute -bottom-8 mx-auto z-10'><h1 className='p-4 text-center font-semibold'>Elige tu destino</h1></div>
                </div>
                <div className="w-full h-1/2 bg-[url('/locations/mazatlan.jpg')] bg-cover bg-center bg-no-repeat flex justify-center">
                    <Link className='absolute mt-28 z-10 text-slate-100 w-fit bg-orange-400 border border-orange-500 bg-opacity-90 p-4 font-bold rounded' href='/depasMaza'>Mazatlán, Sinaloa</Link>
                </div>
                {/* <Link className='left-1/3 absolute z-10 text-slate-950 w-fit bg-slate-200 bg-opacity-20 backdrop-blur-sm p-4 top-20 font-bold' href='/depasBaja'>Los Cabos, Baja California Sur</Link>
        <img className='w-full h-2/5 relative' src='/locations/losCabos.jpg' alt='photo of los cabos san lucas' />
        <div className='bg-orange-400 w-fit border border-orange-700 rounded absolute left-1/3 z-10' style={{ marginTop: '-30px' }}><h1 className='p-4 text'>Elige tu destino</h1></div>
        <Link className='left-1/3 absolute z-10 text-slate-950 w-fit bg-slate-200 bg-opacity-20 backdrop-blur-sm p-4 bottom-72 font-bold' href='/depasMaza'>Mazatlán, Sinaloa</Link>
        <img className='w-full h-1/2' src='/locations/mazatlan.jpg' alt='photo of los cabos san lucas' /> */}
            </main>

            {/* <footer className={styles.footer}>

      </footer> */}
        </div>
    )
}